// Generated by LiveScript 1.5.0
(function(){
  var esprima, walk, list_requires;
  esprima = require('esprima');
  walk = require('esprima-walk');
  list_requires = function(code){
    var parsed, output, output_set;
    parsed = esprima.parse(code, {
      tolerant: true
    });
    output = [];
    output_set = {};
    walk(parsed, function(node){
      var ref$, ref1$, value, ref2$, ref3$;
      if ((node != null ? node.type : void 8) === 'CallExpression' && (node != null ? (ref$ = node.callee) != null ? ref$.type : void 8 : void 8) === 'Identifier' && (node != null ? (ref1$ = node.callee) != null ? ref1$.name : void 8 : void 8) === 'require') {
        value = node != null ? (ref2$ = node.arguments) != null ? (ref3$ = ref2$[0]) != null ? ref3$.value : void 8 : void 8 : void 8;
        if (!output_set[value]) {
          output.push(value);
          return output_set[value] = true;
        }
      }
    });
    return output;
  };
  module.exports = list_requires;
}).call(this);
