// This file is generated from libs_common/function_signatures.ls
// Do not edit this file directly. To regenerate, run gulp
const {import_lib} = require('libs_frontend/import_lib');
module.exports = import_lib('db_utils');
