// Generated by LiveScript 1.4.0
(function(){
  var shuffle, exports;
  shuffle = require('shuffle-array');
  module.exports = exports = function(arr){
    return shuffle(arr, {
      copy: true
    });
  };
}).call(this);
