#!/bin/bash

gulp js_srcgen
gulp livescript_srcgen
./node_modules/documentation-habitlab/bin/documentation.js build src_gen/libs_frontend/*.js src_gen/libs_backend/*.js src_gen/libs_common/*.js -f html -o doc --github