#!/usr/bin/env node

let jsyaml = require('js-yaml')
let fs = require('fs')

let version = jsyaml.safeLoad(fs.readFileSync('src/manifest.yaml', 'utf-8')).version.trim().split('.').join('-')

let netlify = require('netlify')
let getsecret = require('getsecret')

let token = getsecret('netlify_token')

let client = netlify.createClient({access_token: token})

async function main() {
  let site = await client.createSite({
    name: "habitlab-dist-" + version
  })
  console.log('site created: habitlab-dist-' + version)
  let deploy = await site.createDeploy({
    dir: 'dist'
  })
  console.log('deploy started')
  await deploy.waitForReady()
  console.log('deploy finished')
}

main()
